railsproj/config/routes.rb
Rails.application.routes.draw do
	authenticated do
		root :to => 'users#index', as: :authenticated
	end
  	root to: 'visitors#index'
  	devise_for :users
  	resources :groups do
  		resources :users
  	end
  	resources :users do
  		resource :status
  		#delete if want to work
  	end
end

railsproj/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  #def group_name
  #	"#{name}"
  #end
end

railsproj/app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  after_initialize :init
  def init
  	self.description ||= 'Just relaxing~'
  end
  
end

railsproj/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :group
  has_one :status
  after_create :create_status
  geocoded_by :address
  after_initialize :default_address
  after_validation :geocode
  has_attached_file :photo, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"]
  def default_address
  	self.address ||= 'Berkeley, CA'
  end
end

railsproj/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name) }
  end
end

railsproj/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    #Displaying groups; may be unnecessary if we are sticking just one group
    @groups = Group.all
  end

  def show
  	#will show the page for our friend group
  	@group = Group.find(params[:id])
  	#@users = @group.users
  	#Rails.logger.debug("Group id: #{@group.id}")
  	#unless @group.id == current_user.group_id
  	#	redirect_to :back, :alert => "Access denied."
  	#end
  end
end

railsproj/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow "<b>#{user.name}</b> <br> #{user.status.description}"
    end
  end

  def show
    @user = User.find(params[:id])
    @status = @user.status
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  #experiment
  #testing
  def update
    @user = User.find(params[:id])
    @status = @user.status
    if (params[:status] != nil)
      if @status.update_attributes(params[:status].permit(:description))
        redirect_to '/users/'
      end
    else
      if @user.update_attributes(params[:user].permit(:address))
        redirect_to '/users/'
      end
    end
    
  end


  def create
    @user = User.create(user_params)
  end
  private
    def user_params
      params.require(:user).permit(:photo)
    end

end

railsproj/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

railsproj/app/helpers/application_helper.rb
module ApplicationHelper
end

railsproj/app/views/groups/_group.html.erb
<td><%= link_to group.name, group %></td>
<td><%= link_to group.description, group %></td>

railsproj/app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="groups-title">Groups</h3>
      <table class="table">
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <%= render group %>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

railsproj/app/views/groups/show.html.erb
<h3>Group</h3>
<p>Name: <%= @group.name if @group.name %></p>
<p>Email: <%= @group.description if @group.description %></p>
<p>Members:</p>
<% if @users %>
	<% @users.each do |user| %>
    	<%= render user %>
	<% end %> 
<% end %>

railsproj/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

railsproj/app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Roommates', users_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Groups', groups_path %></li>
<% end %>

railsproj/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Roommately', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

railsproj/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

railsproj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsproj" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Railsproj" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

railsproj/app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3 class="about-title">About the Website</h3>
<p class="about-text">
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

railsproj/app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

railsproj/app/views/users/edit.html.erb
<%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
	<%= f.file_field :photo %>
	<%= f.submit 'Update Picture' %>
<% end %>

railsproj/app/views/users/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="container">
  <div class="row">
    <h3 class="users-title">Roommates</h3>
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>


<div class="gmap" style='width: 900px;'>
  <div id="map" style='width: 900px; height: 500px;'></div>
</div>




<script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

railsproj/app/views/users/show.html.erb
<h3>User</h3>
<%= image_tag @user.photo.url %>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

<%= form_for [@user, @status], url: user_path(@user) do |f| %>

	<%= f.text_field :description %></br>
	<%= f.submit 'Update Status' %>

<% end %>
<%= form_for @user, url: user_path(@user) do |f| %>

	<%= f.text_field :address %></br>
	<%= f.collection_radio_buttons :group_id, Group.all, :id, :name %></br>
	<%= f.submit 'Update' %>
	
<% end %>


<%= link_to "Profile Picture", edit_user_path(@user) %>

<!--
<%= form_for @user, url: user_path(@user) do |f| %>

	<%= f.text_field :address %></br>
	<%= f.collection_radio_buttons :group_id, Group.all, :id, :name %></br>
	<%= f.submit 'Update' %>
	
<% end %>
-->

railsproj/app/views/visitors/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Roommately</title>
    <!-- Loading Flat UI -->
    <link href="docs/assets/stylesheets/flat-ui.css" rel="stylesheet">
    <link href="docs/assets/stylesheets/demo.css" rel="stylesheet">
    <link href="docs/assets/stylesheets/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery -->
		<script src="http://code.jquery.com/jquery-latest.min.js"></script>
		<!-- Firebase -->
		<script type='text/javascript' src='https://cdn.firebase.com/js/client/1.0.17/firebase.js'></script>
  </head>
  <body>
<div class="row">
  <p class="tagline">Let your roommates know what you're up to.</p>
  <div class="form-group landing">
    <input type="text" value="" placeholder="What are you up to?" class="form-control message" />
    <p class="enter-text">Press Enter</p>
    <div class="chats" id="chats"></div>
  </div>
</div>

<script>
  var myDataRef = new Firebase("https://infectedchats.firebaseio.com/");

  // attach keypress handler to message input
  $('.message').keypress(function(event) {
    // if user pressed enter
    if (event.keyCode === 13) {
      var userMessage = $('.message').val(); // extract user message

      // construct div with user name and messange and append to chats container
      $('<div/>').text("Update: " + userMessage).appendTo($('.chats'));
      myDataRef.push({ message: userMessage });
    }
  });

</script>
</body>
</html>